/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ControlPanel9f3aRouteImport } from './routes/control-panel-9f3a'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ControlPanel9f3aIndexRouteImport } from './routes/control-panel-9f3a.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as ControlPanel9f3aLoginRouteImport } from './routes/control-panel-9f3a.login'
import { Route as ControlPanel9f3aApplicationsRouteImport } from './routes/control-panel-9f3a.applications'

const ControlPanel9f3aRoute = ControlPanel9f3aRouteImport.update({
  id: '/control-panel-9f3a',
  path: '/control-panel-9f3a',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlPanel9f3aIndexRoute = ControlPanel9f3aIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ControlPanel9f3aRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlPanel9f3aLoginRoute = ControlPanel9f3aLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ControlPanel9f3aRoute,
} as any)
const ControlPanel9f3aApplicationsRoute =
  ControlPanel9f3aApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => ControlPanel9f3aRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/control-panel-9f3a': typeof ControlPanel9f3aRouteWithChildren
  '/control-panel-9f3a/applications': typeof ControlPanel9f3aApplicationsRoute
  '/control-panel-9f3a/login': typeof ControlPanel9f3aLoginRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/control-panel-9f3a/': typeof ControlPanel9f3aIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/control-panel-9f3a/applications': typeof ControlPanel9f3aApplicationsRoute
  '/control-panel-9f3a/login': typeof ControlPanel9f3aLoginRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/control-panel-9f3a': typeof ControlPanel9f3aIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/control-panel-9f3a': typeof ControlPanel9f3aRouteWithChildren
  '/control-panel-9f3a/applications': typeof ControlPanel9f3aApplicationsRoute
  '/control-panel-9f3a/login': typeof ControlPanel9f3aLoginRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/control-panel-9f3a/': typeof ControlPanel9f3aIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/control-panel-9f3a'
    | '/control-panel-9f3a/applications'
    | '/control-panel-9f3a/login'
    | '/jobs/$jobId'
    | '/control-panel-9f3a/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/control-panel-9f3a/applications'
    | '/control-panel-9f3a/login'
    | '/jobs/$jobId'
    | '/control-panel-9f3a'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/control-panel-9f3a'
    | '/control-panel-9f3a/applications'
    | '/control-panel-9f3a/login'
    | '/jobs/$jobId'
    | '/control-panel-9f3a/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ControlPanel9f3aRoute: typeof ControlPanel9f3aRouteWithChildren
  JobsJobIdRoute: typeof JobsJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/control-panel-9f3a': {
      id: '/control-panel-9f3a'
      path: '/control-panel-9f3a'
      fullPath: '/control-panel-9f3a'
      preLoaderRoute: typeof ControlPanel9f3aRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-panel-9f3a/': {
      id: '/control-panel-9f3a/'
      path: '/'
      fullPath: '/control-panel-9f3a/'
      preLoaderRoute: typeof ControlPanel9f3aIndexRouteImport
      parentRoute: typeof ControlPanel9f3aRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-panel-9f3a/login': {
      id: '/control-panel-9f3a/login'
      path: '/login'
      fullPath: '/control-panel-9f3a/login'
      preLoaderRoute: typeof ControlPanel9f3aLoginRouteImport
      parentRoute: typeof ControlPanel9f3aRoute
    }
    '/control-panel-9f3a/applications': {
      id: '/control-panel-9f3a/applications'
      path: '/applications'
      fullPath: '/control-panel-9f3a/applications'
      preLoaderRoute: typeof ControlPanel9f3aApplicationsRouteImport
      parentRoute: typeof ControlPanel9f3aRoute
    }
  }
}

interface ControlPanel9f3aRouteChildren {
  ControlPanel9f3aApplicationsRoute: typeof ControlPanel9f3aApplicationsRoute
  ControlPanel9f3aLoginRoute: typeof ControlPanel9f3aLoginRoute
  ControlPanel9f3aIndexRoute: typeof ControlPanel9f3aIndexRoute
}

const ControlPanel9f3aRouteChildren: ControlPanel9f3aRouteChildren = {
  ControlPanel9f3aApplicationsRoute: ControlPanel9f3aApplicationsRoute,
  ControlPanel9f3aLoginRoute: ControlPanel9f3aLoginRoute,
  ControlPanel9f3aIndexRoute: ControlPanel9f3aIndexRoute,
}

const ControlPanel9f3aRouteWithChildren =
  ControlPanel9f3aRoute._addFileChildren(ControlPanel9f3aRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ControlPanel9f3aRoute: ControlPanel9f3aRouteWithChildren,
  JobsJobIdRoute: JobsJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
