/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ControlPanelRouteImport } from './routes/control-panel'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ControlPanelIndexRouteImport } from './routes/control-panel.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as ControlPanelLoginRouteImport } from './routes/control-panel.login'
import { Route as ControlPanelApplicationsRouteImport } from './routes/control-panel.applications'

const ControlPanelRoute = ControlPanelRouteImport.update({
  id: '/control-panel',
  path: '/control-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlPanelIndexRoute = ControlPanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ControlPanelRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlPanelLoginRoute = ControlPanelLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ControlPanelRoute,
} as any)
const ControlPanelApplicationsRoute =
  ControlPanelApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => ControlPanelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/control-panel': typeof ControlPanelRouteWithChildren
  '/control-panel/applications': typeof ControlPanelApplicationsRoute
  '/control-panel/login': typeof ControlPanelLoginRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/control-panel/': typeof ControlPanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/control-panel/applications': typeof ControlPanelApplicationsRoute
  '/control-panel/login': typeof ControlPanelLoginRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/control-panel': typeof ControlPanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/control-panel': typeof ControlPanelRouteWithChildren
  '/control-panel/applications': typeof ControlPanelApplicationsRoute
  '/control-panel/login': typeof ControlPanelLoginRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/control-panel/': typeof ControlPanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/control-panel'
    | '/control-panel/applications'
    | '/control-panel/login'
    | '/jobs/$jobId'
    | '/control-panel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/control-panel/applications'
    | '/control-panel/login'
    | '/jobs/$jobId'
    | '/control-panel'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/control-panel'
    | '/control-panel/applications'
    | '/control-panel/login'
    | '/jobs/$jobId'
    | '/control-panel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ControlPanelRoute: typeof ControlPanelRouteWithChildren
  JobsJobIdRoute: typeof JobsJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/control-panel': {
      id: '/control-panel'
      path: '/control-panel'
      fullPath: '/control-panel'
      preLoaderRoute: typeof ControlPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-panel/': {
      id: '/control-panel/'
      path: '/'
      fullPath: '/control-panel/'
      preLoaderRoute: typeof ControlPanelIndexRouteImport
      parentRoute: typeof ControlPanelRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-panel/login': {
      id: '/control-panel/login'
      path: '/login'
      fullPath: '/control-panel/login'
      preLoaderRoute: typeof ControlPanelLoginRouteImport
      parentRoute: typeof ControlPanelRoute
    }
    '/control-panel/applications': {
      id: '/control-panel/applications'
      path: '/applications'
      fullPath: '/control-panel/applications'
      preLoaderRoute: typeof ControlPanelApplicationsRouteImport
      parentRoute: typeof ControlPanelRoute
    }
  }
}

interface ControlPanelRouteChildren {
  ControlPanelApplicationsRoute: typeof ControlPanelApplicationsRoute
  ControlPanelLoginRoute: typeof ControlPanelLoginRoute
  ControlPanelIndexRoute: typeof ControlPanelIndexRoute
}

const ControlPanelRouteChildren: ControlPanelRouteChildren = {
  ControlPanelApplicationsRoute: ControlPanelApplicationsRoute,
  ControlPanelLoginRoute: ControlPanelLoginRoute,
  ControlPanelIndexRoute: ControlPanelIndexRoute,
}

const ControlPanelRouteWithChildren = ControlPanelRoute._addFileChildren(
  ControlPanelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ControlPanelRoute: ControlPanelRouteWithChildren,
  JobsJobIdRoute: JobsJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
